// Buildergen generates type-safe builders for annotated structs.
//
// Builders generated by this package make use of one unexported struct
// serving as the builder, and many types with an underlying type identical
// to that of the builder, denoting which fields have been set. This allows
// for a chain of calls building up a type which indicates all required fields
// have been set. These types have an exported method to allow for building the
// struct.
package main
